export interface Pizza {
  id: string;
  name: string;
  tagline: string;
  description: string;
  price: number;
  category: string;
  image: string;
  tags: string[];
  spicyLevel: number; // 0 to 3
  isVeg: boolean;
  calories: number;
  preparationTime: string;
  story: string;
}

export const CATEGORIES = [
  "Veg Pizzas",
  "Non-Veg Pizzas",
  "Calzone",
  "Garlic Breads",
  "Veg Pastas",
  "Non-Veg Pastas",
  "Veg Sandwiches",
  "Non-Veg Sandwiches",
  "Veg Burgers",
  "Non-Veg Burgers",
  "Mocktails",
  "Coffees",
  "Milkshakes",
  "Tea",
  "Starters",
  "Ice Cream"
];

export const PIZZAS: Pizza[] = [
  // =================== VEG PIZZAS ===================
  {
    id: "classic-margarita",
    name: "Classic Margarita",
    tagline: "The blueprint of Neapolitan wood-fired mastery.",
    description: "Traditional marinara sauce with fresh mozzarella cheese and basil.",
    price: 320,
    category: "Veg Pizzas",
    image: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?q=80&w=800&auto=format&fit=crop",
    tags: ["Classic", "Best Seller", "Wood-Fired Heritage"],
    spicyLevel: 0,
    isVeg: true,
    calories: 780,
    preparationTime: "8 Mins",
    story: "Our tribute to Italy's culinary soul. A thin, slow-fermented crust charred to leopard-spotted perfection, holding a melting river of fresh mozzarella and garden basil."
  },
  {
    id: "chilli-margarita",
    name: "Chilli Margarita",
    tagline: "Classic elegance meets a fiery volcanic spark.",
    description: "Classic margarita with a spicy twist of fresh chilli.",
    price: 350,
    category: "Veg Pizzas",
    image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=800&auto=format&fit=crop",
    tags: ["Spicy", "Gen Z Hype"],
    spicyLevel: 2,
    isVeg: true,
    calories: 790,
    preparationTime: "8 Mins",
    story: "We've infused our signature sweet marinara with hand-crushed local chillies, adding a dynamic, warm heat that plays perfectly against the cooling mozzarella."
  },
  {
    id: "corn-margarita",
    name: "Corn Margarita",
    tagline: "Sweet gold kernels on an heritage canvas.",
    description: "Fresh mozzarella cheese and golden corn atop a marinara base.",
    price: 350,
    category: "Veg Pizzas",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=800&auto=format&fit=crop",
    tags: ["Sweet & Salty"],
    spicyLevel: 0,
    isVeg: true,
    calories: 820,
    preparationTime: "9 Mins",
    story: "Every slice offers a sensory snap of sweet roasted golden corn kernels floating in molten mozzarella, layered on a dense, organic dough base."
  },
  {
    id: "margarita-fungi",
    name: "Margarita Fungi",
    tagline: "Earthy, smoky, and absolutely layered.",
    description: "Marinara, mozzarella, and mushrooms.",
    price: 350,
    category: "Veg Pizzas",
    image: "https://images.unsplash.com/photo-1544982503-9f984c14501a?q=80&w=800&auto=format&fit=crop",
    tags: ["Earthy", "Chef's Choice"],
    spicyLevel: 0,
    isVeg: true,
    calories: 810,
    preparationTime: "9 Mins",
    story: "We toss freshly sliced wild forest cremini mushrooms in cold-pressed garlic oil before scattering them across a sea of melting mozzarella."
  },
  {
    id: "margarita-corn-fungi",
    name: "Margarita Corn Fungi",
    tagline: "The perfect sweet-meets-smoky equilibrium.",
    description: "Mozzarella, corn, and mushrooms.",
    price: 350,
    category: "Veg Pizzas",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=800&auto=format&fit=crop",
    tags: ["Rich Texture"],
    spicyLevel: 0,
    isVeg: true,
    calories: 840,
    preparationTime: "10 Mins",
    story: "Earthy, sautéed forest mushrooms paired with the crisp, sweet snap of charred golden corn on our 48-hour signature proofed sourdough."
  },
  {
    id: "pesto-pizza",
    name: "Pesto Pizza",
    tagline: "An editorial statements of green and sweet.",
    description: "Pesto sauce with roasted cherry tomatoes and fresh mozzarella.",
    price: 450,
    category: "Veg Pizzas",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=800&auto=format&fit=crop",
    tags: ["Best Seller", "Nutty & Herbaceous"],
    spicyLevel: 0,
    isVeg: true,
    calories: 890,
    preparationTime: "10 Mins",
    story: "No tomato paste here. We sweep our house-made Sicilian basil-pine nut pesto across the dough, adding blistered cherry tomatoes for juicy acidity."
  },
  {
    id: "farmhouse-pizza",
    name: "Farmhouse Pizza",
    tagline: "A vivid garden party in the wood-fired dome.",
    description: "Mozzarella, corn, mushroom, bell pepper, jalapeños, and black olives.",
    price: 380,
    category: "Veg Pizzas",
    image: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?q=80&w=800&auto=format&fit=crop",
    tags: ["Vibrant Garden", "Crowd Favorite"],
    spicyLevel: 1,
    isVeg: true,
    calories: 870,
    preparationTime: "9 Mins",
    story: "Loaded with colorful bell peppers, wild mushrooms, sweet corn, spicy jalapeños, and ripe black olives to create a deep, layered texture."
  },
  {
    id: "veggie-paradise",
    name: "Veggie Paradise",
    tagline: "Vibrant hues and absolute clean crunch.",
    description: "Capsicum, bell pepper, corn, zucchini, and olives.",
    price: 380,
    category: "Veg Pizzas",
    image: "https://images.unsplash.com/photo-1571066811602-71683a3f680d?q=80&w=800&auto=format&fit=crop",
    tags: ["Fresh Veggies", "Clean Eating"],
    spicyLevel: 0,
    isVeg: true,
    calories: 830,
    preparationTime: "9 Mins",
    story: "Designed for a fresh, lighter feel. We layer charred zucchini, snap capsicum, bright bell peppers, and golden corn on a light marinara sheet."
  },
  {
    id: "mexican-pizza",
    name: "Mexican Pizza",
    tagline: "A dynamic salsa twist that sparks on the tongue.",
    description: "Salsa sauce with bell peppers, jalapeños, and mozzarella.",
    price: 380,
    category: "Veg Pizzas",
    image: "https://images.unsplash.com/photo-1613564834644-a170d95366a1?q=80&w=800&auto=format&fit=crop",
    tags: ["Spicy", "Tangy"],
    spicyLevel: 2,
    isVeg: true,
    calories: 860,
    preparationTime: "10 Mins",
    story: "We replace traditional marinara with a vibrant, zesty salsa base, loading it with sharp jalapeño rounds and blistered bell peppers for high-fashion heat."
  },
  {
    id: "three-pepper-pizza",
    name: "Three Pepper Pizza",
    tagline: "Vibrant capsicum geometry in sweet embers.",
    description: "Marinara and mozzarella with vibrant bell peppers.",
    price: 380,
    category: "Veg Pizzas",
    image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=800&auto=format&fit=crop",
    tags: ["Minimalist"],
    spicyLevel: 0,
    isVeg: true,
    calories: 800,
    preparationTime: "8 Mins",
    story: "A sleek, three-colored pepper mosaic (red, yellow, and green bell peppers) that roasts to sweet perfection under our 900°F live flame."
  },
  {
    id: "cottage-cheese-pizza",
    name: "Cottage Cheese Pizza",
    tagline: "Creamy curd clouds layered in golden cheese.",
    description: "Mozzarella topped with cottage cheese.",
    price: 450,
    category: "Veg Pizzas",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=800&auto=format&fit=crop",
    tags: ["Protein Rich", "Indulgent"],
    spicyLevel: 1,
    isVeg: true,
    calories: 950,
    preparationTime: "10 Mins",
    story: "Soft cubes of hand-pressed organic cottage cheese marinated in delicate herbs, scattered on a dual-cheese mozzarella layout."
  },

  // =================== NON-VEG PIZZAS ===================
  {
    id: "peri-peri-chicken-pizza",
    name: "Peri Peri Chicken Pizza",
    tagline: "Intense spice, smoky chicken, absolute bliss.",
    description: "Spicy peri peri chicken with mozzarella.",
    price: 480,
    category: "Non-Veg Pizzas",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=800&auto=format&fit=crop",
    tags: ["Spicy", "Gen Z Hype", "High Protein"],
    spicyLevel: 3,
    isVeg: false,
    calories: 1020,
    preparationTime: "9 Mins",
    story: "Tender chicken chunks marinated in our aggressive African bird's eye chili blend, balanced by the heavy creaminess of molten fior di latte."
  },
  {
    id: "garlic-chicken-pizza",
    name: "Garlic Chicken Pizza",
    tagline: "Roasted garlic elixir meets tender hearth poultry.",
    description: "Roasted garlic chicken with marinara and mozzarella.",
    price: 480,
    category: "Non-Veg Pizzas",
    image: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?q=80&w=800&auto=format&fit=crop",
    tags: ["Garlicky & Rich", "Comfort Food"],
    spicyLevel: 1,
    isVeg: false,
    calories: 990,
    preparationTime: "10 Mins",
    story: "Slow-roasted chicken breast infused with heavy confit garlic, spread on our dynamic wood-charred crust. Aromatics that instantly satisfy."
  },
  {
    id: "classic-chicken-pizza",
    name: "Classic Chicken Pizza",
    tagline: "The absolute benchmark chicken sourdough.",
    description: "Roasted chicken with olives, jalapeños, and bell peppers.",
    price: 490,
    category: "Non-Veg Pizzas",
    image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=800&auto=format&fit=crop",
    tags: ["Best Seller", "Crowd Pleaser"],
    spicyLevel: 1,
    isVeg: false,
    calories: 1040,
    preparationTime: "9 Mins",
    story: "A perfect harmony of wood-grilled chicken, zesty jalapeños, black olives, and sweet red peppers to provide a full-spectrum epicurean profile."
  },
  {
    id: "chicken-hawaiian-pizza",
    name: "Chicken Hawaiian Pizza",
    tagline: "Controversial sweet and salty editorial statement.",
    description: "Chicken and pineapple with sweet-salty flavour.",
    price: 480,
    category: "Non-Veg Pizzas",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=800&auto=format&fit=crop",
    tags: ["Sweet & Salty", "Editorial"],
    spicyLevel: 0,
    isVeg: false,
    calories: 940,
    preparationTime: "10 Mins",
    story: "Juicy, flame-roasted chicken breast paired with sweet, charred pineapple rounds. An exquisite dynamic taste structure that sparks debate."
  },
  {
    id: "bbq-chicken-pizza",
    name: "BBQ Chicken Pizza",
    tagline: "Smoky sweet glaze on a blistered Neapolitan base.",
    description: "BBQ chicken with onions and peppers.",
    price: 490,
    category: "Non-Veg Pizzas",
    image: "https://images.unsplash.com/photo-1541746972996-4e0b0f43e01a?q=80&w=800&auto=format&fit=crop",
    tags: ["Smoky Sweet", "Trending"],
    spicyLevel: 1,
    isVeg: false,
    calories: 1080,
    preparationTime: "10 Mins",
    story: "Loaded with chicken tossed in heavy hickory smoke barbecue glaze, combined with sweet red onions and blistered bell peppers."
  },

  // =================== CALZONE ===================
  {
    id: "veg-calzone",
    name: "Veg Calzone",
    tagline: "Stuffed golden pockets of pocketed garden heat.",
    description: "Veggies, basil, marinara, and mozzarella wrapped in crust.",
    price: 380,
    category: "Calzone",
    image: "https://images.unsplash.com/photo-1628824851022-e446af7f0591?q=80&w=800&auto=format&fit=crop",
    tags: ["Stuffed Crust", "Cheesy Core"],
    spicyLevel: 1,
    isVeg: true,
    calories: 910,
    preparationTime: "12 Mins",
    story: "We fold our light 48-hour sourdough over a treasure of garden veggies, fresh basil leaves, rich marinara, and double mozzarella, baking it until it inflates with aromatic steam."
  },
  {
    id: "chicken-calzone",
    name: "Chicken Calzone",
    tagline: "Spicy harissa and molten cheese in a golden pocket.",
    description: "Chicken with harissa sauce and mozzarella.",
    price: 450,
    category: "Calzone",
    image: "https://images.unsplash.com/photo-1628824851022-e446af7f0591?q=80&w=800&auto=format&fit=crop",
    tags: ["Best Seller", "Spicy Stuffed"],
    spicyLevel: 2,
    isVeg: false,
    calories: 1050,
    preparationTime: "12 Mins",
    story: "A folded sourdough envelope holding shredded chicken coated in zesty harissa chili paste and double mozzarella, resulting in a molten river of spicy cheese on first cut."
  },

  // =================== GARLIC BREADS ===================
  {
    id: "classic-garlic-bread",
    name: "Classic Garlic Bread",
    tagline: "Crisp artisanal slices tossed in liquid herb gold.",
    description: "Baked bread loaded with our garlic butter and herb mix.",
    price: 130,
    category: "Garlic Breads",
    image: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?q=80&w=800&auto=format&fit=crop",
    tags: ["Classic Side", "Crunchy"],
    spicyLevel: 0,
    isVeg: true,
    calories: 380,
    preparationTime: "6 Mins",
    story: "Crafted from fresh in-house baguettes, brushed with local organic garlic butter and fresh parsley, toasted until golden brown."
  },
  {
    id: "cheese-garlic-bread",
    name: "Cheese Garlic Bread",
    tagline: "Molten premium mozzarella atop garlic crusts.",
    description: "Our signature garlic bread loaded with double melted cheese.",
    price: 160,
    category: "Garlic Breads",
    image: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?q=80&w=800&auto=format&fit=crop",
    tags: ["Cheesy", "Best Seller"],
    spicyLevel: 0,
    isVeg: true,
    calories: 520,
    preparationTime: "7 Mins",
    story: "We pile fresh, shredded mozzarella on garlic buttered bread, baking it under live wood flames until it bubbles and caramelizes."
  },
  {
    id: "garlic-spice-bread",
    name: "Garlic Spice Bread",
    tagline: "Zesty chili flakes and herbs on garlic toast.",
    description: "Spicy and herbaceous garlic bread with an kick.",
    price: 180,
    category: "Garlic Breads",
    image: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?q=80&w=800&auto=format&fit=crop",
    tags: ["Spicy Accent"],
    spicyLevel: 2,
    isVeg: true,
    calories: 460,
    preparationTime: "7 Mins",
    story: "A punchy, spicy twist on our garlic bread using hand-crushed dry red pepper flakes and wild Italian oregano."
  },
  {
    id: "garlic-chicken-bread",
    name: "Garlic Chicken Bread",
    tagline: "Tender shredded chicken over bubbling garlic cheese.",
    description: "Garlic bread topped with seasoned chicken and mozzarella.",
    price: 210,
    category: "Garlic Breads",
    image: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?q=80&w=800&auto=format&fit=crop",
    tags: ["Meat Lovers", "Hearty Side"],
    spicyLevel: 1,
    isVeg: false,
    calories: 610,
    preparationTime: "8 Mins",
    story: "Topped with wood-roasted chicken breast and double mozzarella, baking it until it fuses into a high-protein, savory masterpiece."
  },
  {
    id: "garlic-chicken-jalapeno-bread",
    name: "Garlic Chicken Jalapeno Bread",
    tagline: "The absolute zenith of loaded spicy garlic bread.",
    description: "Seasoned chicken, spicy jalapeños, garlic butter, and cheese.",
    price: 240,
    category: "Garlic Breads",
    image: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?q=80&w=800&auto=format&fit=crop",
    tags: ["Spicy Loaded", "Trending"],
    spicyLevel: 2,
    isVeg: false,
    calories: 640,
    preparationTime: "8 Mins",
    story: "Spicy jalapeño rounds provide a sharp, vinegar-acid kick that perfectly slices through the rich garlic-chicken cheese layers."
  },

  // =================== VEG PASTAS ===================
  {
    id: "aglio-e-olio",
    name: "Aglio e Olio",
    tagline: "Minimalist olive oil, garlic, and spaghetti purity.",
    description: "Classic spaghetti tossed in extra virgin olive oil, toasted garlic, and chili flakes.",
    price: 250,
    category: "Veg Pastas",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop",
    tags: ["Traditional", "Minimalist"],
    spicyLevel: 1,
    isVeg: true,
    calories: 590,
    preparationTime: "8 Mins",
    story: "A masterclass in restraint. We emulsify bronze-cut spaghetti water with single-estate cold-pressed olive oil, toasted garlic chips, and wild red chili."
  },
  {
    id: "spaghetti-pesto",
    name: "Spaghetti Pesto",
    tagline: "Aromatic green pine nut pesto clinging to spaghetti.",
    description: "Spaghetti tossed in rich basil pesto sauce, finished with cherry tomatoes.",
    price: 280,
    category: "Veg Pastas",
    image: "https://images.unsplash.com/photo-1546549032-9571cd6b27df?q=80&w=800&auto=format&fit=crop",
    tags: ["Nutty & Fresh", "Best Seller"],
    spicyLevel: 0,
    isVeg: true,
    calories: 680,
    preparationTime: "9 Mins",
    story: "Crafted with fresh basil crushed in mortar and pestle, blended with toasted pine nuts, aged parmesan, and single-origin olive oil."
  },
  {
    id: "alfredo-pasta",
    name: "Alfredo Pasta",
    tagline: "Velvety, buttery white cream and cheese dream.",
    description: "Penne pasta in a rich, creamy white sauce with Parmesan cheese.",
    price: 230,
    category: "Veg Pastas",
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?q=80&w=800&auto=format&fit=crop",
    tags: ["Creamy Classic", "Comforting"],
    spicyLevel: 0,
    isVeg: true,
    calories: 790,
    preparationTime: "9 Mins",
    story: "A luscious, heavy cream reduction infused with cracked black pepper and freshly grated Parmigiano-Reggiano, clinging to al dente penne."
  },
  {
    id: "arrabbiata-pasta",
    name: "Arrabbiata Pasta",
    tagline: "Aggressive Italian plum tomato sauce with spicy kick.",
    description: "Penne pasta in spicy garlic-infused tomato sauce.",
    price: 230,
    category: "Veg Pastas",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop",
    tags: ["Spicy Tomato", "Acidic & Bright"],
    spicyLevel: 2,
    isVeg: true,
    calories: 550,
    preparationTime: "8 Mins",
    story: "Tossed in slow-cooked San Marzano tomatoes, heavily infused with garlic and red Calabrian chili flakes to spark the palate."
  },
  {
    id: "creamy-mushroom-pasta",
    name: "Creamy Mushroom Pasta",
    tagline: "Forest mushrooms in a decadent garlic cream sauce.",
    description: "Penne pasta with sautéed mushrooms in rich mushroom cream.",
    price: 280,
    category: "Veg Pastas",
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?q=80&w=800&auto=format&fit=crop",
    tags: ["Earthy", "Luxury Cream"],
    spicyLevel: 0,
    isVeg: true,
    calories: 720,
    preparationTime: "10 Mins",
    story: "Rich, earthy sautéed button and cremini mushrooms folded into a thick, garlic-parmesan cream sauce. Luxurious and filling."
  },
  {
    id: "italian-pink-sauce-pasta",
    name: "Italian Pink Sauce Pasta",
    tagline: "The absolute best of red tomato and white cream.",
    description: "Penne in a perfect blend of rich tomato and creamy Alfredo.",
    price: 250,
    category: "Veg Pastas",
    image: "https://images.unsplash.com/photo-1546549032-9571cd6b27df?q=80&w=800&auto=format&fit=crop",
    tags: ["Pink Sauce", "Harmonious"],
    spicyLevel: 1,
    isVeg: true,
    calories: 690,
    preparationTime: "9 Mins",
    story: "Can't decide between tomato and cream? Our signature pink sauce fuses sweet acid San Marzano tomatoes with heavy cream in absolute harmony."
  },

  // =================== NON-VEG PASTAS ===================
  {
    id: "creamy-chicken-pasta",
    name: "Creamy Chicken Pasta",
    tagline: "Alfredo cream paired with pan-roasted chicken.",
    description: "Rich white cream penne pasta loaded with pan-roasted chicken.",
    price: 330,
    category: "Non-Veg Pastas",
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?q=80&w=800&auto=format&fit=crop",
    tags: ["High Protein", "Decadent"],
    spicyLevel: 0,
    isVeg: false,
    calories: 890,
    preparationTime: "10 Mins",
    story: "Juicy pan-roasted chicken breast strips tossed with penne in a bubbling, velvety garlic Alfredo sauce. Ultimate comfort."
  },
  {
    id: "aglio-e-olio-chicken",
    name: "Aglio e Olio With Chicken",
    tagline: "Sleek olive oil pasta elevated with grilled chicken.",
    description: "Spaghetti Aglio e Olio loaded with pan-seared chicken.",
    price: 310,
    category: "Non-Veg Pastas",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop",
    tags: ["Lean & Clean", "Garlicky"],
    spicyLevel: 1,
    isVeg: false,
    calories: 740,
    preparationTime: "9 Mins",
    story: "Tender, grilled chicken strips scattered over a glossy spaghetti bed tossed with organic olive oil, parsley, and garlic chips."
  },
  {
    id: "spaghetti-creamy-garlic-chicken",
    name: "Spaghetti With Creamy Garlic Chicken Sauce",
    tagline: "Pure editorial poultry and heavy cream luxury.",
    description: "Thick, rich garlic chicken reduction tossed with al dente spaghetti.",
    price: 350,
    category: "Non-Veg Pastas",
    image: "https://images.unsplash.com/photo-1546549032-9571cd6b27df?q=80&w=800&auto=format&fit=crop",
    tags: ["Best Seller", "Signature Pasta"],
    spicyLevel: 1,
    isVeg: false,
    calories: 920,
    preparationTime: "11 Mins",
    story: "Double-thick garlic cream reduction holding minced roasted chicken, emulsified over high flame with bronze-cut spaghetti. A true masterpiece."
  },

  // =================== VEG SANDWICHES ===================
  {
    id: "bombay-masala-sandwich",
    name: "Bombay Masala Sandwich",
    tagline: "Street-inspired spiced potato and green chutney fusion.",
    description: "Mint-cilantro chutney, spiced potato mash, and fresh cucumber.",
    price: 230,
    category: "Veg Sandwiches",
    image: "https://images.unsplash.com/photo-1521390188846-e2a3a97453a0?q=80&w=800&auto=format&fit=crop",
    tags: ["Street Food Inspired", "Spicy & Tangy"],
    spicyLevel: 2,
    isVeg: true,
    calories: 450,
    preparationTime: "7 Mins",
    story: "A classic Bombay street tribute. Multi-grain bread loaded with heavily spiced potato mash, sweet tomatoes, crunchy cucumber, and green chutney."
  },
  {
    id: "veg-cheese-grilled-sandwich",
    name: "Veg Cheese Grilled Sandwich",
    tagline: "Crisp grilled toast with melting double cheese.",
    description: "Finely chopped veggies and loaded mozzarella grilled to crunch.",
    price: 180,
    category: "Veg Sandwiches",
    image: "https://images.unsplash.com/photo-1538220856186-0be0c0757984?q=80&w=800&auto=format&fit=crop",
    tags: ["Cheesy Crunch", "Comfort Food"],
    spicyLevel: 0,
    isVeg: true,
    calories: 510,
    preparationTime: "7 Mins",
    story: "Crunchy buttered slices packed with bell peppers, onions, carrots, and an abundance of premium melting mozzarella cheese."
  },
  {
    id: "veg-cheese-sandwich",
    name: "Veg Cheese Sandwich",
    tagline: "Soft deli sandwich packed with cool cheese.",
    description: "Classic cold sandwich with fresh sliced veg and cheese slice.",
    price: 130,
    category: "Veg Sandwiches",
    image: "https://images.unsplash.com/photo-1521390188846-e2a3a97453a0?q=80&w=800&auto=format&fit=crop",
    tags: ["Minimalist", "Light Bite"],
    spicyLevel: 0,
    isVeg: true,
    calories: 390,
    preparationTime: "5 Mins",
    story: "Clean, fresh, and immediate. Buttered soft sandwich bread with crisp cucumber slices, juicy tomato, and a thick slice of cheddar."
  },
  {
    id: "cucumber-delight-sandwich",
    name: "Cucumber Delight Sandwich",
    tagline: "Vibrant cool cucumber and mint cream cheese.",
    description: "Crispy cucumber ribbons with light herb cream cheese spread.",
    price: 260,
    category: "Veg Sandwiches",
    image: "https://images.unsplash.com/photo-1521390188846-e2a3a97453a0?q=80&w=800&auto=format&fit=crop",
    tags: ["Ultra Light", "Clean Living"],
    spicyLevel: 0,
    isVeg: true,
    calories: 320,
    preparationTime: "6 Mins",
    story: "Super-thin fresh cucumber ribbons layered with house-blended dill and green mint cream cheese on soft organic white bread."
  },
  {
    id: "green-goddess-sandwich",
    name: "Green Goddess Sandwich",
    tagline: "Vibrant green avocado, cucumber, and spinach layers.",
    description: "Avocado smash, baby spinach, cucumber, and herbaceous pesto spread.",
    price: 290,
    category: "Veg Sandwiches",
    image: "https://images.unsplash.com/photo-1538220856186-0be0c0757984?q=80&w=800&auto=format&fit=crop",
    tags: ["Best Seller", "Healthy Living"],
    spicyLevel: 0,
    isVeg: true,
    calories: 410,
    preparationTime: "8 Mins",
    story: "Designed like a high-fashion lunch story. Packed with nutrient-dense green ingredients, offering a highly photogenic, clean, and crunchy profile."
  },
  {
    id: "mediterranean-chickpea-sandwich",
    name: "Mediterranean Chickpea Sandwich",
    tagline: "Smashed chickpea hummous and roasted bell peppers.",
    description: "Herbed chickpea mash, olive tapenade, feta cheese, and roasted peppers.",
    price: 300,
    category: "Veg Sandwiches",
    image: "https://images.unsplash.com/photo-1521390188846-e2a3a97453a0?q=80&w=800&auto=format&fit=crop",
    tags: ["Protein Packed", "Mediterranean"],
    spicyLevel: 1,
    isVeg: true,
    calories: 490,
    preparationTime: "8 Mins",
    story: "Earthy smashed seasoned chickpeas layered with creamy feta crumbles, roasted red peppers, and a dense, olive-oil rich tapenade spread."
  },

  // =================== NON-VEG SANDWICHES ===================
  {
    id: "chicken-club-sandwich",
    name: "Chicken Club Sandwich",
    tagline: "Triple-decker stacked with chicken, egg, and greens.",
    description: "Three layers of toasted bread, pulled chicken, fried egg, lettuce, and mayo.",
    price: 280,
    category: "Non-Veg Sandwiches",
    image: "https://images.unsplash.com/photo-1538220856186-0be0c0757984?q=80&w=800&auto=format&fit=crop",
    tags: ["Best Seller", "High Protein", "Indulgent"],
    spicyLevel: 0,
    isVeg: false,
    calories: 780,
    preparationTime: "9 Mins",
    story: "The ultimate club masterpiece. Stacked with savory pulled roasted chicken, a soft fried egg, crunchy cucumber, tomatoes, and smooth garlic aioli."
  },
  {
    id: "roasted-chicken-grilled-sandwich",
    name: "Roasted Chicken Grilled Sandwich",
    tagline: "Smoky shredded chicken and melted cheese.",
    description: "Toasted sourdough bread packed with herb-grilled chicken and mozzarella.",
    price: 250,
    category: "Non-Veg Sandwiches",
    image: "https://images.unsplash.com/photo-1538220856186-0be0c0757984?q=80&w=800&auto=format&fit=crop",
    tags: ["Meat Lovers", "Comfort Food"],
    spicyLevel: 1,
    isVeg: false,
    calories: 620,
    preparationTime: "8 Mins",
    story: "Crisp, buttery grilled sourdough holding hot shredded chicken breast tossed in organic herbs, complete with pullable mozzarella layers."
  },

  // =================== VEG BURGERS ===================
  {
    id: "herb-burger",
    name: "Herb Burger",
    tagline: "Crispy potato herb patty in a buttery brioche.",
    description: "Veg patty infused with green herbs, lettuce, tomato, and house mayo.",
    price: 160,
    category: "Veg Burgers",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?q=80&w=800&auto=format&fit=crop",
    tags: ["Crispy", "Classic Veg"],
    spicyLevel: 0,
    isVeg: true,
    calories: 490,
    preparationTime: "7 Mins",
    story: "Tender, crispy-fried potato and green peas patty seasoned with fresh dill, parsley, and garlic, resting in toasted warm brioche buns."
  },
  {
    id: "aloo-tikki-burger",
    name: "Aloo Tikki Burger",
    tagline: "Desi spiced potato crunch with tangy sauce.",
    description: "Crispy aloo tikki patty with spicy tomato-mayo sauce and onions.",
    price: 130,
    category: "Veg Burgers",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?q=80&w=800&auto=format&fit=crop",
    tags: ["Local Heritage", "Crispy & Spicy"],
    spicyLevel: 2,
    isVeg: true,
    calories: 440,
    preparationTime: "6 Mins",
    story: "A crunchy fried golden potato patty infused with cumin, coriander, and dry mango powder, topped with spicy dressing and red onion."
  },
  {
    id: "veggie-burger",
    name: "Veggie Burger",
    tagline: "Our bestseller garden burger stacked with cheese.",
    description: "Thick vegetable mix patty, cheese slice, lettuce, pickle, and secret burger glaze.",
    price: 170,
    category: "Veg Burgers",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?q=80&w=800&auto=format&fit=crop",
    tags: ["BESTSELLER", "Loaded Veg"],
    spicyLevel: 1,
    isVeg: true,
    calories: 550,
    preparationTime: "8 Mins",
    story: "A delicious, heavy patty crafted from carrots, peas, corn, and potatoes, topped with melted cheese, dill pickles, and our signature spread."
  },
  {
    id: "fiery-paneer-burger",
    name: "Fiery Paneer Burger",
    tagline: "Crispy paneer slab dipped in aggressive hot glaze.",
    description: "Heavy crispy batter-fried cottage cheese block with spicy sriracha sauce.",
    price: 200,
    category: "Veg Burgers",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?q=80&w=800&auto=format&fit=crop",
    tags: ["Spicy Paneer", "Cheese Melt"],
    spicyLevel: 3,
    isVeg: true,
    calories: 680,
    preparationTime: "9 Mins",
    story: "A massive, crispy cornflake-crusted organic paneer block, slathered in an aggressive chili glaze and cooling mayo. Extreme crunch."
  },
  {
    id: "zesty-jalapeno-veg-burger",
    name: "Zesty Jalapeño Veg Burger",
    tagline: "Tangy jalapeño cheese core on crunchy veg.",
    description: "Crispy vegetable patty with pickled jalapeños and jalapeño cheese sauce.",
    price: 170,
    category: "Veg Burgers",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?q=80&w=800&auto=format&fit=crop",
    tags: ["Zesty Heat"],
    spicyLevel: 2,
    isVeg: true,
    calories: 520,
    preparationTime: "8 Mins",
    story: "Zesty pickled jalapeño rounds provide a strong, acidic heat that perfectly offsets the crispy golden vegetable patty."
  },

  // =================== NON-VEG BURGERS ===================
  {
    id: "golden-crunch-chicken-burger",
    name: "Golden Crunch Chicken Burger",
    tagline: "Extreme crispy batter-fried chicken breast.",
    description: "Extra crispy chicken breast, shredded lettuce, and creamy black pepper mayo.",
    price: 200,
    category: "Non-Veg Burgers",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop",
    tags: ["Crispy Fried", "Protein Heavy"],
    spicyLevel: 1,
    isVeg: false,
    calories: 690,
    preparationTime: "8 Mins",
    story: "Buttermilk-brined chicken breast coated in a double-dredged flaky crust, fried golden, topped with heavy black pepper mayo."
  },
  {
    id: "smoky-roast-chicken-burger",
    name: "Smoky Roast Chicken Burger",
    tagline: "Flame-grilled chicken patty with hickory glaze.",
    description: "Char-grilled ground chicken patty, caramelized onions, BBQ sauce, and cheese.",
    price: 230,
    category: "Non-Veg Burgers",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop",
    tags: ["Flame Grilled", "Smoky"],
    spicyLevel: 1,
    isVeg: false,
    calories: 610,
    preparationTime: "9 Mins",
    story: "A ground chicken patty seasoned with secret spices, char-grilled over real hickory embers, topped with melting cheddar and sweet onions."
  },
  {
    id: "grande-chicken-burger",
    name: "Grande Chicken Burger",
    tagline: "The absolute peak of loaded chicken burgers.",
    description: "Double crispy chicken patty, fried egg, cheese slice, pickle, and premium burger sauce.",
    price: 270,
    category: "Non-Veg Burgers",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop",
    tags: ["BESTSELLER", "Extreme Loaded", "Chef's Special"],
    spicyLevel: 2,
    isVeg: false,
    calories: 940,
    preparationTime: "11 Mins",
    story: "A colossal double-decker chicken burger loaded with premium cheddar cheese, a soft fried egg, and tangy pickles. Pure food luxury."
  },

  // =================== MOCKTAILS ===================
  {
    id: "cranberry-sangria",
    name: "Cranberry Sangria",
    tagline: "Vibrant tart cranberry and fresh fruit infusion.",
    description: "Rich cranberry juice, sparkling soda, apple chips, and orange rounds.",
    price: 150,
    category: "Mocktails",
    image: "https://images.unsplash.com/photo-1536935338788-846bb9981813?q=80&w=800&auto=format&fit=crop",
    tags: ["Signature Drink", "Fruity Refreshment"],
    spicyLevel: 0,
    isVeg: true,
    calories: 120,
    preparationTime: "3 Mins",
    story: "Served in a premium highball glass. Tart cranberry base combined with organic blood orange juice and cold, fizzy soda."
  },
  {
    id: "watermelon-mojito",
    name: "Watermelon Mojito",
    tagline: "Cool sweet melon with fresh muddled mint.",
    description: "Fresh watermelon chunks, lime juice, mint leaves, and white sugar syrup.",
    price: 150,
    category: "Mocktails",
    image: "https://images.unsplash.com/photo-1513530534585-c7b1394c6d51?q=80&w=800&auto=format&fit=crop",
    tags: ["Summer Favorite", "Hydrating"],
    spicyLevel: 0,
    isVeg: true,
    calories: 110,
    preparationTime: "3 Mins",
    story: "We crush fresh sweet watermelon and garden-grown mint leaves directly in the serving glass, finishing with a zesty citrus spray."
  },
  {
    id: "tropical-punch",
    name: "Tropical Punch",
    tagline: "A vibrant sunshine blend of citrus fruits.",
    description: "Pineapple, orange, mango, and passion fruit juice with premium ginger ale.",
    price: 150,
    category: "Mocktails",
    image: "https://images.unsplash.com/photo-1536935338788-846bb9981813?q=80&w=800&auto=format&fit=crop",
    tags: ["Citrus Splash", "Sunny Vibe"],
    spicyLevel: 0,
    isVeg: true,
    calories: 140,
    preparationTime: "4 Mins",
    story: "A delightful collision of sweet mango pulp, zesty pineapple extract, and organic passion fruit juice. Highly photogenic."
  },
  {
    id: "strawberry-apple-punch",
    name: "Strawberry Apple Punch",
    tagline: "Fruity red berries and crisp green apples.",
    description: "Red strawberry puree, green apple juice, mint, and mineral soda.",
    price: 150,
    category: "Mocktails",
    image: "https://images.unsplash.com/photo-1536935338788-846bb9981813?q=80&w=800&auto=format&fit=crop",
    tags: ["Berry Sweet"],
    spicyLevel: 0,
    isVeg: true,
    calories: 130,
    preparationTime: "3 Mins",
    story: "Sweet strawberry purees floating gracefully inside sparkling green apple juice, garnished with organic apple skin curls."
  },
  {
    id: "lemon-soda",
    name: "Lemon Soda",
    tagline: "The timeless fizzy citrus thirst quencher.",
    description: "Fresh squeezed lemon juice, sparkling water, option of salt or sweet.",
    price: 60,
    category: "Mocktails",
    image: "https://images.unsplash.com/photo-1513530534585-c7b1394c6d51?q=80&w=800&auto=format&fit=crop",
    tags: ["Timeless", "Hydrating"],
    spicyLevel: 0,
    isVeg: true,
    calories: 40,
    preparationTime: "2 Mins",
    story: "Organic lemons squeezed directly over solid crystal ice blocks, topped with premium sparkling spring water."
  },

  // =================== COFFEES ===================
  {
    id: "black-coffee",
    name: "Black Coffee",
    tagline: "Pure double shot single-origin espresso elixir.",
    description: "Freshly pulled espresso shot with hot water. Clean and strong.",
    price: 50,
    category: "Coffees",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=800&auto=format&fit=crop",
    tags: ["Keto Friendly", "Pure Caffeine"],
    spicyLevel: 0,
    isVeg: true,
    calories: 5,
    preparationTime: "2 Mins",
    story: "No milk, no sugar, just the absolute chocolate-nutty complexity of our dark roasted Ethiopian Arabica beans."
  },
  {
    id: "classic-coffee",
    name: "Classic Coffee",
    tagline: "Traditional steamed milk espresso latte.",
    description: "Espresso shot with steamed milk and a thin layer of micro-foam.",
    price: 70,
    category: "Coffees",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=800&auto=format&fit=crop",
    tags: ["Classic Latte", "Comfort Brew"],
    spicyLevel: 0,
    isVeg: true,
    calories: 120,
    preparationTime: "3 Mins",
    story: "A smooth, creamy morning ritual. Espresso blended with perfectly textured warm milk for a comforting chocolate-malt balance."
  },
  {
    id: "hot-chocolate",
    name: "Hot Chocolate",
    tagline: "Pure liquid dark hazelnut chocolate elixir.",
    description: "Thick melted Belgian dark chocolate whisked with steaming cream.",
    price: 199,
    category: "Coffees",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop",
    tags: ["Best Seller", "Chocolate Heaven"],
    spicyLevel: 0,
    isVeg: true,
    calories: 450,
    preparationTime: "4 Mins",
    story: "We melt actual cocoa bars in heavy milk cream, finishing with cocoa dust. Extremely thick, glossy, and indulgent."
  },
  {
    id: "cold-coffee",
    name: "Cold Coffee",
    tagline: "Creamy iced milk coffee, sweet and refreshing.",
    description: "Double shot espresso blended with chilled milk and premium vanilla cream.",
    price: 190,
    category: "Coffees",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop",
    tags: ["Classic Cold", "Summer Favorite"],
    spicyLevel: 0,
    isVeg: true,
    calories: 320,
    preparationTime: "3 Mins",
    story: "A thick, velvety blend of cold milk, Arabica espresso, and organic sugar, whipped until a thick foam forms on top."
  },
  {
    id: "chocolate-cold-coffee",
    name: "Chocolate Cold Coffee",
    tagline: "Decadent dark chocolate mocha milkshake combo.",
    description: "Cold coffee blended with dark Belgian cocoa syrup and cream.",
    price: 200,
    category: "Coffees",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop",
    tags: ["Mocha Twist", "Decadent"],
    spicyLevel: 0,
    isVeg: true,
    calories: 390,
    preparationTime: "3 Mins",
    story: "Rich chocolate ganache glazed around the serving glass, filled to the brim with creamy iced whipped mocha latte."
  },
  {
    id: "vanilla-iced-coffee",
    name: "Vanilla Iced Coffee",
    tagline: "Subtle sweet vanilla bean notes on cold caffeine.",
    description: "Double espresso poured over ice blocks, milk, and vanilla bean syrup.",
    price: 200,
    category: "Coffees",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop",
    tags: ["Vanilla Bean", "Subtle Sweet"],
    spicyLevel: 0,
    isVeg: true,
    calories: 240,
    preparationTime: "3 Mins",
    story: "Sweet vanilla bean extract perfectly balances the bold, smoky tones of roasted coffee beans over large ice cubes."
  },
  {
    id: "iced-americano",
    name: "Iced Americano",
    tagline: "Sleek matte black caffeine shot over solid ice.",
    description: "Double shot espresso poured over cold water and ice.",
    price: 140,
    category: "Coffees",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=800&auto=format&fit=crop",
    tags: ["Minimalist", "Zero Sugar"],
    spicyLevel: 0,
    isVeg: true,
    calories: 5,
    preparationTime: "2 Mins",
    story: "Ethiopian single-origin espresso pulled over mineral ice chunks, offering a refreshing, floral caffeine kick."
  },
  {
    id: "chocolate-peanut-butter-iced-coffee",
    name: "Chocolate Peanut Butter Iced Coffee",
    tagline: "A masterclass in thick creamy nutty energy.",
    description: "Cold coffee blended with organic peanut butter and dark cocoa.",
    price: 210,
    category: "Coffees",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop",
    tags: ["Trending", "Nutty & Sweet"],
    spicyLevel: 0,
    isVeg: true,
    calories: 490,
    preparationTime: "4 Mins",
    story: "A luxurious breakfast/dessert hybrid. Packed with high protein natural peanut butter, dark chocolate syrup, and fresh espresso."
  },

  // =================== MILKSHAKES ===================
  {
    id: "passion-fruit-milkshake",
    name: "Passion Fruit Milkshake",
    tagline: "Tropical exotic passion fruit cream dream.",
    description: "Thick vanilla ice cream blended with fresh passion fruit pulp.",
    price: 210,
    category: "Milkshakes",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=800&auto=format&fit=crop",
    tags: ["Signature Shake", "Exotic Taste"],
    spicyLevel: 0,
    isVeg: true,
    calories: 480,
    preparationTime: "4 Mins",
    story: "A delightful balance of creamy, high-fat vanilla ice cream and the sharp, tropical citrus snap of actual passion fruit puree."
  },
  {
    id: "strawberry-milkshake",
    name: "Strawberry Milkshake",
    tagline: "Classic pink shake using real garden berries.",
    description: "Strawberries blended with milk and strawberry ice cream.",
    price: 190,
    category: "Milkshakes",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=800&auto=format&fit=crop",
    tags: ["Berry Delight", "Classic Shake"],
    spicyLevel: 0,
    isVeg: true,
    calories: 420,
    preparationTime: "3 Mins",
    story: "No artificial pink syrups here. We blend actual frozen organic strawberries with rich whole milk and fresh vanilla cream."
  },
  {
    id: "mango-milkshake",
    name: "Mango Milkshake",
    tagline: "Decadent Alfonso mango pulp creaminess.",
    description: "Sweet mango chunks blended with cream and milk.",
    price: 190,
    category: "Milkshakes",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=800&auto=format&fit=crop",
    tags: ["Seasonal Hype"],
    spicyLevel: 0,
    isVeg: true,
    calories: 440,
    preparationTime: "3 Mins",
    story: "Celebrating the king of Indian fruits. Sweet, golden Alfonso mango pulp blended into an ultra-thick, luscious summer beverage."
  },
  {
    id: "chocolate-milkshake",
    name: "Chocolate Milkshake",
    tagline: "Liquid cocoa paradise with chocolate dust.",
    description: "Double chocolate ice cream blended with dark fudge sauce.",
    price: 190,
    category: "Milkshakes",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=800&auto=format&fit=crop",
    tags: ["Comforting", "Chocolate Heaven"],
    spicyLevel: 0,
    isVeg: true,
    calories: 520,
    preparationTime: "3 Mins",
    story: "Decadent double chocolate cream whipped with dark fudge syrup, creating a rich, glossy chocolate landscape in the mouth."
  },
  {
    id: "dry-fruit-milkshake",
    name: "Dry Fruit Milkshake",
    tagline: "Elite nut and honey energetic blend.",
    description: "Almonds, cashews, pistachios, dates, and honey blended in milk.",
    price: 240,
    category: "Milkshakes",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=800&auto=format&fit=crop",
    tags: ["Best Seller", "Nutrient Dense"],
    spicyLevel: 0,
    isVeg: true,
    calories: 590,
    preparationTime: "5 Mins",
    story: "A royal treatment. Packed with crushed premium pistachios, almonds, and walnuts, sweetened naturally with crushed dates and wild forest honey."
  },

  // =================== TEA ===================
  {
    id: "masala-tea",
    name: "Masala Tea",
    tagline: "Warm aromatic spiced milk chai.",
    description: "Brewed black tea leaves with milk, cardamom, cloves, ginger, and sugar.",
    price: 30,
    category: "Tea",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=800&auto=format&fit=crop",
    tags: ["Desi Classic", "Spiced Aromas"],
    spicyLevel: 1,
    isVeg: true,
    calories: 60,
    preparationTime: "3 Mins",
    story: "Slow-simmered Indian heritage tea brewed with fresh crushed green cardamom pods, sharp ginger slices, and sweet spices."
  },
  {
    id: "ginger-tea",
    name: "Ginger Tea",
    tagline: "Warm, sharp fresh ginger tea for the senses.",
    description: "Simmered black tea with heavy fresh ginger juice and milk.",
    price: 50,
    category: "Tea",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=800&auto=format&fit=crop",
    tags: ["Immunity Boost", "Comforting"],
    spicyLevel: 1,
    isVeg: true,
    calories: 55,
    preparationTime: "3 Mins",
    story: "A soothing cup brewed with aggressively crushed fresh organic ginger root, providing a pleasant, fiery kick at the throat."
  },
  {
    id: "lemon-tea",
    name: "Lemon Tea",
    tagline: "Clear citrus black tea, light and clean.",
    description: "Clear brewed black tea with lemon juice and organic honey.",
    price: 90,
    category: "Tea",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=800&auto=format&fit=crop",
    tags: ["Antioxidant", "Light Bite"],
    spicyLevel: 0,
    isVeg: true,
    calories: 25,
    preparationTime: "2 Mins",
    story: "Clean, fresh, and soothing. Made with premium Darjeeling tea leaves, squeezed organic lemon juice, and a splash of wild honey."
  },
  {
    id: "green-tea",
    name: "Green Tea",
    tagline: "Pure hand-plucked steamed tea leaves.",
    description: "Steeped premium organic green tea leaves. Zero calories.",
    price: 90,
    category: "Tea",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=800&auto=format&fit=crop",
    tags: ["Detox", "Zero Calories"],
    spicyLevel: 0,
    isVeg: true,
    calories: 0,
    preparationTime: "2 Mins",
    story: "Pure antioxidant green tea leaves steeped gently at 175°F to ensure a clean, earthy sweet taste without any bitterness."
  },
  {
    id: "lemon-iced-tea",
    name: "Lemon Iced Tea",
    tagline: "Chilled zesty clear tea over solid ice.",
    description: "Cold brewed black tea shaken with lemon syrup and mint.",
    price: 160,
    category: "Tea",
    image: "https://images.unsplash.com/photo-1497515114629-f71d768fd07c?q=80&w=800&auto=format&fit=crop",
    tags: ["Best Seller", "Thirst Quencher"],
    spicyLevel: 0,
    isVeg: true,
    calories: 90,
    preparationTime: "2 Mins",
    story: "A delightful afternoon refresher. Shaken vigorously with zesty lemon extracts, served ice-cold in a tall glass with fresh mint leaves."
  },
  {
    id: "peach-iced-tea",
    name: "Peach Iced Tea",
    tagline: "Exquisite sweet peach stone-fruit juice iced tea.",
    description: "Cold brewed tea infused with sweet peach syrup and mint.",
    price: 180,
    category: "Tea",
    image: "https://images.unsplash.com/photo-1497515114629-f71d768fd07c?q=80&w=800&auto=format&fit=crop",
    tags: ["Stone Fruit Sweet", "Trending"],
    spicyLevel: 0,
    isVeg: true,
    calories: 110,
    preparationTime: "2 Mins",
    story: "A beautiful, copper-hued iced beverage blending sweet, organic peach syrups and bold black tea, served over solid crystal ice."
  },
  {
    id: "passion-fruit-iced-tea",
    name: "Passion Fruit Iced Tea",
    tagline: "Tropical passion fruit citrus clear cold tea.",
    description: "Chilled tea infused with passion fruit pulp and ice blocks.",
    price: 180,
    category: "Tea",
    image: "https://images.unsplash.com/photo-1497515114629-f71d768fd07c?q=80&w=800&auto=format&fit=crop",
    tags: ["Exotic Drink"],
    spicyLevel: 0,
    isVeg: true,
    calories: 110,
    preparationTime: "2 Mins",
    story: "A vibrant, tropical twist. Tangy passion fruit seeds and pulps shaken with light black tea, offering high-fidelity fruit complexity."
  },

  // =================== STARTERS ===================
  {
    id: "french-fries-salted",
    name: "French Fries (Simply Salted)",
    tagline: "Crisp potato batons tossed in sea salt dust.",
    description: "Golden fries simply tossed with fine sea salt.",
    price: 110,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?q=80&w=800&auto=format&fit=crop",
    tags: ["Classic Starter", "Crunchy"],
    spicyLevel: 0,
    isVeg: true,
    calories: 310,
    preparationTime: "5 Mins",
    story: "Perfectly skin-on, double-cooked potato batons to provide a crisp exterior with a soft fluffy potato interior."
  },
  {
    id: "french-fries-peri-peri",
    name: "French Fries (Peri Peri)",
    tagline: "Aggressive zesty African peri-peri spice dust.",
    description: "Golden crispy fries tossed in fiery peri-peri seasoning.",
    price: 150,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?q=80&w=800&auto=format&fit=crop",
    tags: ["Spicy Crunch", "Best Seller"],
    spicyLevel: 2,
    isVeg: true,
    calories: 320,
    preparationTime: "5 Mins",
    story: "Tossed inside a hot bowl with our aggressively spiced bird's eye chili powder, onion extracts, and garlic dust."
  },
  {
    id: "french-fries-cheese",
    name: "French Fries (Cheese)",
    tagline: "Rich creamy cheddar sauce over crispy potatoes.",
    description: "Golden fries slathered in warm melted cheese sauce.",
    price: 150,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?q=80&w=800&auto=format&fit=crop",
    tags: ["Cheesy Heaven"],
    spicyLevel: 0,
    isVeg: true,
    calories: 450,
    preparationTime: "6 Mins",
    story: "A decadent heap of golden potatoes bathed under a generous layer of our signature warm cheddar sauce. Messy and delicious."
  },
  {
    id: "french-fries-peri-cheese",
    name: "French Fries (Peri Peri With Cheese)",
    tagline: "Fiery red spices meets molten cheddar sauce.",
    description: "Fiery peri-peri dusted fries smothered in warm cheese sauce.",
    price: 200,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?q=80&w=800&auto=format&fit=crop",
    tags: ["Spicy & Cheesy", "Trending"],
    spicyLevel: 2,
    isVeg: true,
    calories: 480,
    preparationTime: "6 Mins",
    story: "The ultimate hybrid. Spiced peri peri heat playing directly against the warm, heavy, sweet-salty layer of liquid cheddar."
  },
  {
    id: "french-fries-mexican",
    name: "French Fries (Mexican)",
    tagline: "Salsa, jalapeños, and cheddar cheese heap.",
    description: "Fries loaded with zesty salsa, pickled jalapeño slices, and cheese sauce.",
    price: 280,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?q=80&w=800&auto=format&fit=crop",
    tags: ["Loaded Starter", "Tangy & Spicy"],
    spicyLevel: 2,
    isVeg: true,
    calories: 520,
    preparationTime: "7 Mins",
    story: "Designed like a high-fashion sharing platter. Packed with bold salsa, hot jalapeño cuts, and a thick layer of melted cheese."
  },
  {
    id: "cheese-corn-nuggets",
    name: "Cheese Corn Nuggets",
    tagline: "Golden crispy bites with molten sweet cheese.",
    description: "Breaded nuggets packed with sweet golden corn and gooey cheese.",
    price: 160,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800&auto=format&fit=crop",
    tags: ["Bite Sized", "Gooey Core"],
    spicyLevel: 0,
    isVeg: true,
    calories: 390,
    preparationTime: "6 Mins",
    story: "A thin crispy breaded outer shell holding a molten pocket of cheddar cheese and juicy sweet golden corn. Watch out, it's hot."
  },
  {
    id: "veg-nuggets",
    name: "Veg Nuggets",
    tagline: "Crisp potato and garden vegetable bites.",
    description: "Seasoned vegetable nuggets breaded and crispy-fried.",
    price: 150,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800&auto=format&fit=crop",
    tags: ["Crispy", "Easy Bite"],
    spicyLevel: 0,
    isVeg: true,
    calories: 340,
    preparationTime: "5 Mins",
    story: "Soft mixed garden vegetables rolled in fine panko breadcrumbs, fried until light golden brown. Served with green garlic dip."
  },
  {
    id: "potato-kiwi",
    name: "Potato Kiwi",
    tagline: "Crisp spiced potato wedges with sweet-tangy glaze.",
    description: "Unique crisp roasted potato wedges tossed in kiwi-herb reduction.",
    price: 180,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?q=80&w=800&auto=format&fit=crop",
    tags: ["Innovative", "Sweet & Sour"],
    spicyLevel: 1,
    isVeg: true,
    calories: 360,
    preparationTime: "6 Mins",
    story: "Our unique signature innovation. Crispy-skinned skin-on potato wedges glazed in a sweet-sour, vibrant green kiwi-mint reduction."
  },
  {
    id: "chicken-popcorn",
    name: "Chicken Popcorn",
    tagline: "Tiny crunchy bites of buttermilk-brined chicken.",
    description: "Bite-sized chicken breast pieces coated in a flaky breading and crispy-fried.",
    price: 190,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800&auto=format&fit=crop",
    tags: ["Snack Pick", "Best Seller"],
    spicyLevel: 1,
    isVeg: false,
    calories: 480,
    preparationTime: "6 Mins",
    story: "Dredged in our seasoned flour mix, these bite-sized pops offer a loud, crunchy sound and juicy chicken interiors. Addictive."
  },
  {
    id: "chicken-nuggets",
    name: "Chicken Nuggets",
    tagline: "Timeless classic crispy ground chicken nuggets.",
    description: "Golden fried seasoned ground chicken nuggets served with garlic mayo.",
    price: 200,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800&auto=format&fit=crop",
    tags: ["Classic Starter"],
    spicyLevel: 0,
    isVeg: false,
    calories: 420,
    preparationTime: "5 Mins",
    story: "Finely ground chicken breast seasoned with light pepper and garlic, fried to a crisp golden brown."
  },
  {
    id: "chicken-wings",
    name: "Chicken Wings",
    tagline: "Flame-charred chicken wings glazed in barbecue spice.",
    description: "Juicy chicken wings tossed in our signature smoky BBQ spice sauce.",
    price: 220,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800&auto=format&fit=crop",
    tags: ["Smoky Sweet", "Finger Licking"],
    spicyLevel: 2,
    isVeg: false,
    calories: 590,
    preparationTime: "8 Mins",
    story: "Roasted in our high-heat volcanic oven before getting tossed in a thick, sticky caramelised hickory barbecue reduction."
  },
  {
    id: "chicken-fries",
    name: "Chicken Fries",
    tagline: "Thin elongated crisp chicken strips.",
    description: "Elegantly shaped chicken breast strips crispy-fried to crunch.",
    price: 250,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800&auto=format&fit=crop",
    tags: ["High Protein", "Fun Shape"],
    spicyLevel: 1,
    isVeg: false,
    calories: 510,
    preparationTime: "7 Mins",
    story: "Crispy chicken breast pressed into easy finger-sized strips, breaded and seasoned, offering a convenient high-protein snack."
  },

  // =================== ICE CREAM ===================
  {
    id: "ice-cream-vanilla",
    name: "Vanilla Ice Cream",
    tagline: "Pure classic cold Madagascan vanilla bean.",
    description: "Creamy vanilla bean ice cream scoop.",
    price: 90,
    category: "Ice Cream",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop",
    tags: ["Traditional Sweet"],
    spicyLevel: 0,
    isVeg: true,
    calories: 180,
    preparationTime: "1 Min",
    story: "Crafted with actual organic black vanilla seed specks and heavy farm-fresh milk cream. Pure and authentic."
  },
  {
    id: "ice-cream-butterscotch",
    name: "Butterscotch Ice Cream",
    tagline: "Creamy crunch of golden burnt brown butter candy.",
    description: "Creamy butterscotch scoop loaded with caramelized nut crunch.",
    price: 90,
    category: "Ice Cream",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop",
    tags: ["Crunchy Sweet", "Crowd Favorite"],
    spicyLevel: 0,
    isVeg: true,
    calories: 220,
    preparationTime: "1 Min",
    story: "A delightful collision of smooth, buttery cold cream and actual crunchy bits of caramelized cashew nougat."
  },
  {
    id: "ice-cream-strawberry",
    name: "Strawberry Ice Cream",
    tagline: "Creamy pink vanilla scoop loaded with real strawberry puree.",
    description: "Classic pink strawberry scoop made with real berries.",
    price: 90,
    category: "Ice Cream",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop",
    tags: ["Berry Fresh"],
    spicyLevel: 0,
    isVeg: true,
    calories: 190,
    preparationTime: "1 Min",
    story: "Made with sweet, crushed organic strawberries, resulting in a fresh fruit acidity playing beautifully in cold cream."
  },
  {
    id: "ice-cream-mango",
    name: "Mango Ice Cream",
    tagline: "Tropical Alphonso mango gold scoop.",
    description: "Sweet, creamy mango pulp churned into cold ice cream.",
    price: 90,
    category: "Ice Cream",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop",
    tags: ["Exotic Scoop"],
    spicyLevel: 0,
    isVeg: true,
    calories: 190,
    preparationTime: "1 Min",
    story: "Rich golden mango pulp churned continuously with sweet thick cream to represent the absolute peak of summer."
  },
  {
    id: "ice-cream-chocolate",
    name: "Chocolate Ice Cream",
    tagline: "Pure heavy dark Belgian cacao scoop.",
    description: "Decadent dark chocolate ice cream scoop.",
    price: 90,
    category: "Ice Cream",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop",
    tags: ["Chocolate Heaven"],
    spicyLevel: 0,
    isVeg: true,
    calories: 230,
    preparationTime: "1 Min",
    story: "Deep, rich, and slightly bitter Belgian cocoa melted in fresh milk cream, whipped into a silky dark chocolate landscape."
  },
  {
    id: "ice-cream-sundae",
    name: "Sundae Ice Cream",
    tagline: "Colossal multi-scoop creation with fudge and nuts.",
    description: "Vanilla and chocolate scoops topped with dark fudge glaze, nuts, and cherry.",
    price: 170,
    category: "Ice Cream",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop",
    tags: ["Best Seller", "Editorial Dessert"],
    spicyLevel: 0,
    isVeg: true,
    calories: 490,
    preparationTime: "3 Mins",
    story: "An absolute visual masterpiece. Dual scoops piled high under hot chocolate drizzle, crushed roasted almonds, and a sweet glazed cherry."
  }
];

export const REVIEWS = [
  {
    id: "1",
    name: "Alessia Thorne",
    role: "Vogue Creative Director",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop",
    rating: 5,
    text: "Moonlight Cafe is a total sensory masterpiece. The matte black tables, the amber glows, and the leopard-spotted Pesto Pizza make it feel more like a Paris fashion event than a cafe.",
    date: "May 2026"
  },
  {
    id: "2",
    name: "Kaelen Zhang",
    role: "Culinary Tech Critic",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop",
    rating: 5,
    text: "As a traditionalist who loves modern minimalism, I was ready to be skeptical. But their slow-fermented classic sourdough has the perfect structural integrity and a rich wood-fire char that is absolutely flawless.",
    date: "April 2026"
  },
  {
    id: "3",
    name: "Sasha Dupont",
    role: "Aesthetic Influencer",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop",
    rating: 5,
    text: "The cranberry sangria served next to a piping hot peri peri chicken pizza is literally the most photogenic dinner on the planet. I've posted it three times, and my DMs are absolutely blowing up.",
    date: "May 2026"
  }
];

export interface InstagramPost {
  id: string;
  url: string;
  caption: string;
  likes: string;
  comments: string;
  type: "reel" | "post";
  postUrl?: string;
}

export const INSTAGRAM_POSTS: InstagramPost[] = [
  {
    id: "p1",
    url: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=600&auto=format&fit=crop",
    caption: "Leopard-spotted Neapolitan crust proofed for 48 hours. 🍕🔥",
    likes: "2.4k",
    comments: "86",
    type: "reel",
    postUrl: "https://www.instagram.com/reel/DW3ptzjiafP/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="
  },
  {
    id: "p2",
    url: "https://images.unsplash.com/photo-1546549032-9571cd6b27df?q=80&w=600&auto=format&fit=crop",
    caption: "Al dente perfection. Our fresh handcrafted pasta tossed in rich authentic sauces. 🍝✨",
    likes: "1.8k",
    comments: "42",
    type: "reel",
    postUrl: "https://www.instagram.com/reel/DWlB5gtiWu4/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="
  },
  {
    id: "p3",
    url: "https://images.unsplash.com/photo-1541746972996-4e0b0f43e01a?q=80&w=600&auto=format&fit=crop",
    caption: "Meeting the 900°F heat of our volcanic clay wood-fired oven. Built for the perfect char. 🔥🏽",
    likes: "3.1k",
    comments: "104",
    type: "reel",
    postUrl: "https://www.instagram.com/reel/DOyfTTQCTCx/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="
  },
  {
    id: "p4",
    url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=600&auto=format&fit=crop",
    caption: "Our cozy, warm amber-lit sanctuary. The ultimate spot for your cozy evening escapes. 🌙☕",
    likes: "1.5k",
    comments: "38",
    type: "post",
    postUrl: "https://www.instagram.com/p/DPZHVS0ifsV/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="
  },
  {
    id: "p5",
    url: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?q=80&w=600&auto=format&fit=crop",
    caption: "Decadence layered in cocoa. Indulge in our classic homemade Italian Tiramisu. 🍮🍫",
    likes: "2.2k",
    comments: "59",
    type: "post",
    postUrl: "https://www.instagram.com/p/DVLQfLGiPuw/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="
  },
  {
    id: "p6",
    url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=600&auto=format&fit=crop",
    caption: "Where beautiful vibes meet artisanal wood-fired craft in Kolhapur. Book your table tonight. 🍷🍂",
    likes: "2.9k",
    comments: "73",
    type: "post",
    postUrl: "https://www.instagram.com/p/DYZvFm-iEjn/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="
  }
];
